name: router_annotation
description: Flutter Router Annotation.
version: 2.0.0
homepage: https://github.com/LebranD/router_kit

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test:

  pedantic:
