name: router_annotation
description: Flutter Router Annotation.
version: 2.0.0
homepage: https://github.com/LebranD/router_kit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  page_transition: ^2.0.9

dev_dependencies:
  test:

  pedantic:
