name: router_api
description: Flutter Router Api.
version: 2.0.0
homepage: https://github.com/LebranD/router_kit

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:
